# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matt Lim
title:
email: milttam1@gmail.com
website: https://milttam.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username: milttam
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: milttam1
linkedin_username: matt-lim-1a5128213
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Lim_Matt_Headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Matt and I'm a CS student @CornellUniversity. \
  I am a highly motivated individual interested in software engineering and API design

  I am most skilled in: <mark>Full-Stack Dev</mark> and <mark>Data Science</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Multi-user Social Media App
        link: https://github.com/Milttam/sns-application
        description: | # this will include new lines to allow paragraphs
          - A multi-user social media application built using the <mark>MERN stack</mark> 
          - Developed a RESTful API using Node.js and Express.js, and used OAuth 2.0 
          - Utilized React and Redux to create a multi-component responsive front-end
      - layout: top-left
        title: Verses-API
        link: https://github.com/Milttam/verses-api
        description: | # this will include new lines to allow paragraphs
          - An API that enables users to query for Bible verses and passages
          - Leveraged <mark>MySQL</mark> to store and retrieve data, and Express.js for routing 
          - Secured using <mark>API Keys</mark>, rate limiting, and snyk.io for vulnerability scanning
      - layout: top-left
        title: Encrypted Email System
        link: https://github.com/Milttam/email-system
        description: | # this will include new lines to allow paragraphs
          - Designed and developed an email system encrypted with Diffie-Hellman Key Exchange and a block cipher inspired by the Advanced Encryption Standard (AES)/Rijndael specifications
          - 2000 LoC implemented entirely from scratch in <mark>OCaml</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Availity/Cornell University
        link: https://github.com/address-matching
        # link_text: boringcompany.com
        sub_title: Data Science Fellow
        caption: Jan 2023 - Dec 2023
        description: | # this will include new lines to allow paragraphs
          - Collaborated with Availity, a healthcare IT company, and Cornell Operations Research faculty to design a data science solution to verify information in medical provider directories
          - Significantly enhanced the data-driven decision-making process in Availity's smart alert email system to request for more accurate information from over 2 million providers
          - Implemented, trained, and tuned models using synthetically generated datasets, and optimized accuracy scores using <mark>Python</mark> and <mark>TensorFlow</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cornell University
        caption: 2022-2025 (Expected)
        sub_title: B.S. in Computer Science & Minor in Operations Research
        # quote: >
        #   quote.
        description: | # this will include new lines to allow paragraphs
          Relavent Coursework:\
          CS 2110: Object-Oriented Programming and Data Structures \
          ENGRI 1101: Introduction to Operations Research\
          ECE 2720: Data Science for Engineers\
          CS 2800: Discrete Structure\
          MATH 2940: Linear Algebra for Engineers\
          CS 4780: Machine Learning\
          ECON 3130: Probability and Statistics\
          CS 3110: Functional Programming\
          (DIS Stockholm) App Development\
          (DIS Stoclholm) Data Visualization

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my hobbies and interests include:
      - Coffee making/bean hunting
      - Cycling
      - Photography

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
